services:
  server:
    image: novadityap/blog-platform-server-test
    build:
      context: ./server
      dockerfile: Dockerfile
    command: >
      sh -c "
        npm run seed &&
        npm run test
      "
    env_file:
      - ./server/.env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - blog-platform-test

  client:
    image: novadityap/blog-platform-client-test
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run build
    env_file:
      - ./client/.env
    depends_on:
      server:
        condition: service_completed_successfully
    networks:
      - blog-platform-test

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - blog-mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blog-platform-test

networks:
  blog-platform-test:
